// LEGAL DISCLAIMER (dev/maintainer note, not shown to users):
// Reasonable MVP starting draft, NOT reviewed by a lawyer. Before public
// launch, have counsel review this in full — "Limitation of Liability"
// and "Governing Law" in particular vary significantly by jurisdiction
// and need real legal input, not placeholder text.
//
// TODO(i18n): English-only for now (see the matching note in Privacy.tsx
// for why this isn't in i18n/translations.ts) — should eventually get
// UZ/RU/ZH/DE/FR versions to match the rest of the app.
import { LegalLayout } from "@/components/legal/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="July 30, 2026">
      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Verso (the "Service"), you agree to be bound by these Terms of
          Service. If you do not agree, please do not use the Service.
        </p>
      </section>

      <section>
        <h2>2. Description of Service</h2>
        <p>
          Verso is an editorial travel atlas covering fifty-one countries. It provides
          country-level reference information (currency, entry requirements, seasons and emergency
          numbers), AI-assisted itinerary suggestions ("Verso AI"), a catalogue of places,
          restaurants, hotels and services, user-submitted reviews, and tools to save places and
          build a trip plan.
        </p>
      </section>

      <section>
        <h2>3. Account Registration</h2>
        <p>You agree to provide accurate information when creating an account and to keep it
          up to date. You're responsible for keeping your password secure and for all activity
          under your account. Each person may register only one account.</p>
      </section>

      <section>
        <h2>4. Guest Access</h2>
        <p>You can browse places, read reviews, and use Verso AI without creating an account.
          Saving places to a trip plan, submitting reviews under your name, and syncing your data
          across devices require a signed-in account.</p>
      </section>

      <section>
        <h2>5. AI-Generated Content Disclaimer</h2>
        <p>
          <strong>Verso AI can make mistakes. Check important information.</strong> Responses from
          Verso AI — including recommended itineraries, prices, opening hours, travel times, and
          other travel details — are generated by an AI model and may contain errors or outdated
          information. Always verify critical details (prices, hours, visa requirements, transport
          schedules, etc.) independently with an official or up-to-date source before making
          travel decisions.
        </p>
      </section>

      <section>
        <h2>6. User-Generated Content (Reviews)</h2>
        <p>You retain ownership of reviews and content you submit. By submitting a review, you
          grant Verso a license to display it within the app. You agree not to submit fake,
          misleading, or paid-for reviews. We reserve the right to remove any content that
          violates these Terms or our community guidelines.</p>
      </section>

      <section>
        <h2>7. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Scrape, crawl, or systematically extract data from the Service without permission</li>
          <li>Abuse, spam, or attempt to manipulate Verso AI's outputs</li>
          <li>Use the Service for any unlawful purpose</li>
          <li>Impersonate any person or entity</li>
        </ul>
      </section>

      <section>
        <h2>8. Third-Party Places &amp; Services</h2>
        <p>Verso provides information about third-party locations, restaurants, hotels, and
          service providers for informational purposes. We do not operate these businesses and are
          not responsible for the accuracy of their listed details, their availability, pricing,
          or the quality of service they provide.</p>
      </section>

      <section>
        <h2>9. Intellectual Property</h2>
        <p>The Verso name, logo, and original app content (excluding user-submitted reviews and
          third-party place information) are the property of Verso and may not be used without
          permission.</p>
      </section>

      <section>
        <h2>10. Limitation of Liability</h2>
        <p>To the fullest extent permitted by law, Verso is not liable for travel decisions made
          based on information in the app, losses or damages incurred during travel, or failures,
          errors, or unavailability of third-party places or services referenced in the app.
          The Service is provided "as is" without warranties of any kind.</p>
      </section>

      <section>
        <h2>11. Termination</h2>
        <p>We may suspend or terminate accounts that violate these Terms, engage in abusive
          behavior, or pose a security risk to the Service.</p>
      </section>

      <section>
        <h2>12. Governing Law</h2>
        <p className="italic text-[var(--muted-foreground)]">
          [PLACEHOLDER: governing law and jurisdiction — to be filled in based on where the
          business operating Verso is legally registered]
        </p>
      </section>

      <section>
        <h2>13. Changes to These Terms</h2>
        <p>We may update these Terms from time to time. Material changes will be reflected by
          updating the "Last updated" date above.</p>
      </section>

      <section>
        <h2>14. Contact</h2>
        <p>
          Questions about these Terms? Contact us at{" "}
          <span className="italic text-[var(--muted-foreground)]">
            [PLACEHOLDER: support email]
          </span>.
        </p>
      </section>
    </LegalLayout>
  );
}
